import React from "react";

export const metadata = {
  title: "Articels",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <div>
      <h1>Title</h1>
      <div
        style={{
          background: "blue",
          padding: "25px",
          marginTop: "50px",
          width: "500px",
          borderRadius: "15px",
        }}
      >
        {children}
      </div>
    </div>
  );
}
